### ISSUE TITLE
Update README with windows user instructions

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/support_tunnel#15]

**Comment by rtertiaer** [comment]
#16 ?

**Comment by SteveMicroNova** [comment]
Yes, I'd say that PR covers this issue
I wasn't able to merge at the time due to not having signed commits, and github seems disinterested in taking my authentication keys so I haven't been able to sign it either

Not that I've tried in a while, that was the blocker at the time though

**Comment by rtertiaer** [comment]
cool, I'll keep this open until you get your code signing straightened out.
