### ISSUE TITLE
fab list isn't human readable

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/support_tunnel#22]
Running `fab list` prints the details of every support tunnel ever made in a comma-separated list but with no particular grouping so it just becomes an illegible wall of text

I'd say have some of these things expire from the list when they've been deactivated for x time period, or if we're interested in retaining all of them for internal documentation I might suggest that we be able to pass an arg to limit the number / age of output results

**Comment by rtertiaer** [comment]
This was intentional and I don't consider this a bug; pipe the output through `jq` and filter it there if you want to manipulate the data.

If you feel like adding a date limiting feature here, feel free. I thought I added something like 'list-running-*' so maybe that's actually what you want?
